### ISSUE TITLE
Switch to official Drupal core Composer project template

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/drupal-for-kubernetes#24]
In the docs and in general...

See: https://www.drupal.org/node/3082474

    composer -n create-project drupal/recommended-project:^8.8@dev my-project

Instead of using the composer-template project that I've been using in the past.

Related:

  - https://github.com/geerlingguy/raspberry-pi-dramble/issues/165
  - https://github.com/geerlingguy/ansible-role-drupal/issues/72

**Comment by paul-m** [comment]
Just a heads-up that if you create-project without @dev, you won't get embedded repos:
```
composer -n --prefer-dist create-project drupal/recommended-project:^8.8 my-project
```

**Comment by geerlingguy** [comment]
Related:

  - [How to switch from this composer template to the drupal/recommended-project template?](https://github.com/drupal-composer/drupal-project/issues/535) — mostly I want to get rid of the `ScriptHandler.php` dependency.
  - [Add gitignore(s) to composer-ready project templates](https://www.drupal.org/project/drupal/issues/3082958#comment-13381816)
