### ISSUE TITLE
Broken link in Wiki for 'Dog Bone' stackable case

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/drupal-for-kubernetes#36]
```
<td>
  <a href="https://www.ebay.com/itm/271648357906">Raspberry Pi 'Dog Bone' Stackable</a>
  <a href="https://www.amazon.com/Yahboom-Raspberry-Cluster-6-Layers-Enclosure/.......">&nbsp;Case</a>
</td>
```

Oops! Credit to @mglaman for finding this over in https://github.com/geerlingguy/raspberry-pi-dramble/issues/181

**Comment by decoded-cipher** [comment]
@geerlingguy 
I'm planning to build a **6 Node RPi4 Cluster**. But in India, it seems that the **Dog Bone Stackable Cases** are too expensive. 
Can I somehow get a template file so that I could laser-cut clear acrylic and build a similar case on my own...

**Comment by geerlingguy** [comment]
I'm guessing someone else has a template out there, I just don't have it since I bought the case off eBay pre-cut.
