### ISSUE TITLE
Is it possible to include setup as part of the Docker image or K8s manifest?

### ISSUE THREAD

**Issue by yuriaru** [geerlingguy/drupal-for-kubernetes#39]
I would like to automate the Drupal setup as much as possible. This will include automating the setup wizard using drush. Not sure if that can be part of the Dockerfile or included in a K8s deployment object. The end goal is to have users looking at the site when they open the browser and not going through the setup.

**Comment by geerlingguy** [comment]
For this particular project, I don't want to automate the install using `drush`—I figure that is something you can either do one-off for a single site (like this project does), or automate in a tool that manages your cluster itself (e.g. if you're building tons of sites).
