### ISSUE TITLE
Impossible to remove the pidramble_default_content module

### ISSUE THREAD

**Issue by jessicacavestro1978** [geerlingguy/drupal-for-kubernetes#41]
I tried to remove the custom module : **drush pm:uninstall pidramble_default_content**

The error is: 
[error]  Error: Call to a member function delete() on null in pidramble_default_content_uninstall() (line 26 of /var/www/html/web/modules/custom/pidramble_default_content/pidramble_default_content.install) #0 [internal function]: pidramble_default_content_uninstall(false)
#1 /var/www/html/web/core/lib/Drupal/Core/Extension/ModuleHandler.php(392): call_user_func_array('pidramble_defau...', Array)
#2 /var/www/html/web/core/lib/Drupal/Core/Extension/ModuleInstaller.php(433): Drupal\Core\Extension\ModuleHandler->invoke('pidramble_defau...', 'uninstall', Array)
#3 /var/www/html/web/core/lib/Drupal/Core/ProxyClass/Extension/ModuleInstaller.php(91): Drupal\Core\Extension\ModuleInstaller->uninstall(Array, true)
#4 /var/www/html/vendor/drush/drush/src/Drupal/Commands/pm/PmCommands.php(116): Drupal\Core\ProxyClass\Extension\ModuleInstaller->uninstall(Array, true)
#5 [internal function]: Drush\Drupal\Commands\pm\PmCommands->uninstall(Array, Array)
#6 /var/www/html/vendor/consolidation/annotated-command/src/CommandProcessor.php(257): call_user_func_array(Array, Array)
#7 /var/www/html/vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback(Array, Object(Consolidation\AnnotatedCommand\CommandData))
#8 /var/www/html/vendor/consolidation/annotated-command/src/CommandProcessor.php(176): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter(Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#9 /var/www/html/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(302): Consolidation\AnnotatedCommand\CommandProcessor->process(Object(Symfony\Component\Console\Output\ConsoleOutput), Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#10 /var/www/html/vendor/symfony/console/Command/Command.php(255): Consolidation\AnnotatedCommand\AnnotatedCommand->execute(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/html/vendor/symfony/console/Application.php(1005): Symfony\Component\Console\Command\Command->run(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/html/vendor/symfony/console/Application.php(255): Symfony\Component\Console\Application->doRunCommand(Object(Consolidation\AnnotatedCommand\AnnotatedCommand), Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/html/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/html/vendor/drush/drush/src/Runtime/Runtime.php(118): Symfony\Component\Console\Application->run(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/html/vendor/drush/drush/src/Runtime/Runtime.php(48): Drush\Runtime\Runtime->doRun(Array, Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/html/vendor/drush/drush/drush.php(72): Drush\Runtime\Runtime->run(Array)
#17 /var/www/html/vendor/drush/drush/includes/preflight.inc(18): require('/var/www/html/v...')
#18 phar:///usr/local/bin/drush/bin/drush.php(141): drush_main()
#19 /usr/local/bin/drush(10): require('phar:///usr/loc...')
#20 {main}. 

Could you fix it? Thanks

**Comment by geerlingguy** [comment]
That particular example is not meant to be changed—instead you would substitute your own Drupal site if you want a custom Drupal site.

To modify the pidramble codebase would require some extra effort and a pretty deep knowledge of Drupal internals due to the way the pidramble.com website works.
