### ISSUE TITLE
Integrate / Support Blackfire

### ISSUE THREAD

**Issue by kamal2222ahmed** [geerlingguy/drupal-for-kubernetes#47]
It would be helpful to integrate Blackfire (https://blackfire.io ) with drupal-for-kubernetes, so we can apply the same configuration to production k8s.

**Comment by geerlingguy** [comment]
I have an Ansible role I use for it on some servers: https://github.com/geerlingguy/ansible-role-blackfire

But I tend to have a separate build for dev that might have extra tools like Blackfire integrated. I don't want to add it or other similar profiling tools into this project at this time.
