### ISSUE TITLE
This example seems for drupal on containers not Kubenetes?

### ISSUE THREAD

**Issue by venkateshakarle** [geerlingguy/drupal-for-kubernetes#51]
Hi,

I want to run Drupal on Kubernetes Pods. so landed on this example.
but I see you have added docker-compose file with instructions to use docker containers to run the application.

there seems to be no Orchestration tool configured? I don't see any K8s config files or instructions.

Could you please let us know if this is stored some where? or may change the naming to correct purpose if not? 

Thanks in advance.

**Comment by geerlingguy** [comment]
@venkateshakarle - Please see the project documentation: https://github.com/geerlingguy/drupal-for-kubernetes/blob/master/docs/README.md

It has instructions for how to build out a Drupal site inside Kubernetes. The compose file is meant to help debug the Drupal container locally without Kubernetes if desired.

**Comment by venkateshakarle** [comment]
Thanks a lot @geerlingguy .
Looks great.
